version: "3.8"

services:
  movie-service:
    image: ${{ secrets.DOCKER_USER }}/movie-service:latest
    ports:
      - 8081:8081
    environment:
      DATABASE_HOST: mongo-products
      DATABASE_PORT: 27018

  visitor-service:
    image: ${{ secrets.DOCKER_USER }}/visitor-service:latest
    ports:
      - 8082:8082
    environment:
      DATABASE_HOST: mongo-products
      DATABASE_PORT: 27017

  auditorium-service:
    image: ${{ secrets.DOCKER_USER }}/auditorium-service:latest
    ports:
      - 8084:8084
    environment:
      DATABASE_HOST: mysql-inventory
      DATABASE_PORT: 3307

  reservation-service:
    image: ${{ secrets.DOCKER_USER }}/reservation-service:latest
    ports:
      - 8083:8083
    environment:
      DATABASE_HOST: mysql-order
      DATABASE_PORT: 3308
  
  api-gateway:
   depends_on:
     - movie-service
     - reservation-service
     - visitor-servie
     - auditorium-service
   image: miverboven/ede-api-gateway
   ports:
     - 8085:8085
   links:
     - movie-service
     - reservation-service
     - visitor-servie
     - auditorium-service
   environment:
     MOVIE_SERVICE_BASEURL: movie-service:8081
     RESERVATION_SERVICE_BASEURL: reservation-service:8083
     VISITOR_SERVICE_BASEURL: visitor-service:8082
     AUDITORIUM_SERVICE_BASEURL: auditorium-service:8084

volumes:
  mongodb_product_data:
  mysql_inventory_data:
  mysql_order_data:
